### ISSUE TITLE
Version 1.4.1 uses AndroidX instead of Support library

### ISSUE THREAD

**Issue by yonghow** [snowplow/snowplow-android-tracker#373]
Hi,

My app is still using android.support library and it is working with version 1.2.1

I upgraded to version 1.4.1 and it throws class not found exception for `Landroidx/lifecycle/ProcessLifecycleOwner;`

Do we have to migrate to androidx library when using version 1.4.1?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sg.trackerdemoapp, PID: 4942
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ProcessLifecycleOwner;
        at com.snowplowanalytics.snowplow.tracker.Tracker$1.run(Tracker.java:497)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ProcessLifecycleOwner" on path: DexPathList[[zip file "/data/app/sg.trackerdemoapp-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.snowplowanalytics.snowplow.tracker.Tracker$1.run(Tracker.java:497) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    	Suppressed: java.lang.ClassNotFoundException: androidx.lifecycle.ProcessLifecycleOwner
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 10 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

compileSdkVersion 28
minSdkVersion 15
targetSdkVersion 28
versionCode 1

**Comment by AlexBenny** [comment]
Hi @yonghow , thanks for raising this issue.
The new version introduced a breaking change using androidx rather than android.support.
That migration will be introduced in the next major version.
We are now reverting to `android.support` in order to avoid breaking changes and the fix will be released soon in the next patch version `1.4.2`.

**Comment by wogaa** [comment]
I tried with version 1.4.2 and still having the same issue with the following error

```
2020-06-06 11:02:54.581 8926-8926/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sg.wogaa.trackerdemoapp, PID: 8926
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/ProcessLifecycleOwner;
        at com.snowplowanalytics.snowplow.tracker.Tracker$1.run(Tracker.java:497)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.ProcessLifecycleOwner" on path: DexPathList[[zip file "/data/app/sg.wogaa.trackerdemoapp-7_JMuUwFr4J2qBBUWMMSSQ==/base.apk"],nativeLibraryDirectories=[/data/app/sg.wogaa.trackerdemoapp-7_JMuUwFr4J2qBBUWMMSSQ==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.snowplowanalytics.snowplow.tracker.Tracker$1.run(Tracker.java:497) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by AlexBenny** [comment]
Thanks @wogaa for reporting this.
I wonder if it can be caused by cache issues.
Would you mind cleaning the cache and let us know any outcome?
- `Build -> Clean Project`
- `File -> Invalidate Caches / Restart...`
It can require a few attempts.

If it doesn't work, please, could you provide some more info about device, Android version and if it works correctly with old tracker versions (< 1.4.0)?

**Comment by AlexBenny** [comment]
Closing for inactivity
